### ISSUE TITLE
JSON-LD 1.1 interest

### ISSUE THREAD

**Issue by fils** [piprate/json-gold#2]
I am curious if JSON-LD 1.1 is on the roadmap for this package.  

https://json-ld.org/spec/latest/json-ld/

json-gold has been so wonderful to have and I'm just curious as I see 1.1 addressing some of the issues of multiple types and also being able to integrate things like GeoJSON elements into the JSON-LD object. 

Thanks!
Doug

**Comment by kazarena** [comment]
@fils the short answer is yes, absolutely. I've already put in some minor provisions to support it.

The long answer is: I haven't been following the latest development of this standard (since Dec 2017) and not 100% sure how stable it is. Also, the usefulness of this package (at least for us) depends on how up to date the other implementations are (JavaScript, Python and Java in particular).

Do you think it's a good time to start supporting 1.1?

**Comment by BigBlueHat** [comment]
> Do you think it's a good time to start supporting 1.1?

Definitely! Full disclosure: I'm one of the Co-Chairs of the @w3c [JSON-LD Working Group](https://www.w3.org/2018/json-ld-wg/) 😸

It would be great to have you join us as an implementer/tester as well as involved in the discussions around JSON-LD's future.

You can get involved via [our various GitHub repos](https://github.com/topics/json-ld-wg) or [join the W3C](https://www.w3.org/Consortium/join) and then join the JSON-LD WG to get involved in our weekly phone discussions.

Regardless of what involvement you have time for, we'd appreciate the feedback you can contribute!

Thanks!
🎩

**Comment by kazarena** [comment]
@BigBlueHat, I would be delighted help. We are actively using JSON-LD for the last 3 years and further development of the standard is of the utmost importance for us.

I'll take a look at the WG repos you mentioned. Any hints where my input would be most useful are welcome.

**Comment by BigBlueHat** [comment]
The [syntax](https://github.com/w3c/json-ld-syntax/) and [api](https://github.com/w3c/json-ld-api/) repos are likely of the greatest interest at this point. You can see more about what we plan to accomplish in [our charter](https://json-ld.github.io/charter/).

The other big area we could use help with is testing. We'll be continuing to use the current JSON-LD [testing suite](https://json-ld.org/test-suite/) and at some point there will be an official W3C testing environment and process to get a "gold star" 🥇 as a [conforming implementation](https://json-ld.org/test-suite/reports/)--JSON-goLD is [already listed there](https://json-ld.org/test-suite/reports/#subj_8) in fact! 😁 

Lastly, there's a [public mailing list](https://lists.w3.org/Archives/Public/public-json-ld-wg/) where you can see some discussions and the posting of the call agenda and minutes each week. If you dig in deep enough, we'd also love to have you on the calls where final decisions are made by the group.

Thanks for all you're doing, and it's great to hear you've got so much experience with JSON-LD!

**Comment by kazarena** [comment]
@BigBlueHat thanks for all the details.

It's our goal to always have 100% pass rate for the relevant test suite. By the way, providing this suite is a fantastic way to help JSON-LD developers with new implementations, it can't go any better!

**Comment by kazarena** [comment]
@fils @BigBlueHat, we have implemented the initial support for JSON-LD 1.1 spec, see https://github.com/piprate/json-gold/pull/15. All 1.1 tests from the current official test suite pass, with an exception of 5 advanced framing tests. We don't support _omitGraph_ option yet. I'll try to fix a couple of remaining tests, but this implementation is good enough to go live, in my opinion.

Having looked at the 1.1 spec in great detail I must say it's very good!

**Comment by kazarena** [comment]
Added _omitGraph_ support and fixed 2 framing tests. The only outstanding broken framing test is **tg010**, see https://github.com/piprate/json-gold/issues/13. I thought it's related to a different behaviour in 1.1, but it appears to have a different issue with document base. Will describe in #13.

**Comment by fils** [comment]
@kazarena Thanks for this!     I am going to be in D.C. next week for some coding time with others in my group.  I'll definitely put this on our agenda.  I'm particularly interested in seeing if this makes some spatial data (as in GeoJSON) integration easier.  

We got some more funding to continue our work with schema.org integration with federal earth science facilities.    So this is well timed...

great news!

**Comment by kazarena** [comment]
@fils I'm looking forward to hearing about your experience.

In the meantime, we got a new version out (0.2.0) that includes 1.1 support.

**Comment by BigBlueHat** [comment]
Great to hear about the progress @kazarena! Another great reference implementation is @gkellogg's [Ruby-based implementation for RDF.rb](https://github.com/ruby-rdf/json-ld/). Gregg is the primary editor for the three JSON-LD specs, so his implementation tends to stay in sync more than most. 😄 

Thanks for the great work you're doing here!

**Comment by gkellogg** [comment]
The json-ld.org version of the test suite is frozen from work done by the community group. The working group spec references the up-to-date test suite at w3c.github.io/json-ld-api/tests. Framing has its own test suite.

Both python and JavaScript mplementations are somewhat behind the latest version of the specs.

**Comment by kazarena** [comment]
@gkellogg many thanks for the pointer. I've taken the tests from the repos mentioned above and raised a new PR. There are a lot of additions, and the pass rate dropped to 87% (see the conformance report [here](https://github.com/piprate/json-gold/blob/a4f0487067f4ae6de5e0e32c80f6aa2ba9f66ce4/conformance_report.jsonld)). I implemented some of the smaller updates and marked the remaining unsupported/failing tests as to-be-skipped for now. The largest outstanding areas are HTML based tests (not sure when I'll look at these ones), list-of-lists, sealed contexts, stricter validation. The rest are various edge cases across all the operations. I'll turn it into _issues_ and will deal with them when time permits.

There were several surprises. For instance, three toRdf tests which were passing before, started failing  after the test file update. It's related to the order of quads:

### Old output (toRdf-0106-out.nq)

```
<http://example.com/people/dave> <http://xmlns.com/foaf/0.1/knows> <http://example.com/people/markus> .
<http://example.com/people/dave> <http://xmlns.com/foaf/0.1/name> "Dave Longley" .
<http://example.com/people/markus> <http://xmlns.com/foaf/0.1/name> "Markus Lanthaler" .
<https://json-ld.org/test-suite/tests/relative-node> <http://example.com/vocab/noTerm> <http://example.com/people/markus> .
<https://json-ld.org/test-suite/tests/relative-node> <http://xmlns.com/foaf/0.1/name> "Compact keys using @vocab" .
```

### New output (toRdf-0106-out.nq)

```
<http://example.com/people/markus> <http://xmlns.com/foaf/0.1/name> "Markus Lanthaler" .
<http://example.com/people/dave> <http://xmlns.com/foaf/0.1/name> "Dave Longley" .
<http://example.com/people/dave> <http://xmlns.com/foaf/0.1/knows> <http://example.com/people/markus> .
<https://w3c.github.io/json-ld-api/tests/toRdf/relative-node> <http://xmlns.com/foaf/0.1/name> "Compact keys using @vocab" .
<https://w3c.github.io/json-ld-api/tests/toRdf/relative-node> <http://example.com/vocab/noTerm> <http://example.com/people/markus> .
```

The only difference is the order of quads. My implementation (in line with Python and Java versions) sorts the quads as the last step. The spec doesn't mention ordering, and the test suite docs explicitly recommend comparing the outputs of ToRDF operation semantically, so no reliance on order. Sorting the quads was always a major performance hit and a limiting factor for streaming. I would love to get rid of it. What are you thoughts? Is it safe to stop sorting ToRDF output?

**Comment by gkellogg** [comment]
The spec has relaxed the requirements on blank node labeling to conform with RDF norms. You can no longer depend on the order of quads.  The test README says to use RDF isomorphism, but you could also use normalization to test the results.

Note, there is a broad change in test strategy to relax strict order and blank node naming.

**Comment by kazarena** [comment]
@gkellogg thanks, I'll update the testing methodology and it will fix 3-4 older tests.

**Comment by kazarena** [comment]
@fils @gkellogg @BigBlueHat,

I've created a new PR that implements a good chunk of the current JSON-LD 1.1 specification, see https://github.com/piprate/json-gold/pull/24.

Test suite conformance is at around 89%, ex. Framing. See the latest conformance report [here](https://github.com/piprate/json-gold/blob/json11-dec-2019/conformance_report.jsonld). Please note that I'm not using RDF isomorphism yet for test checks, and there are around 10 tests for the ToRDF algorithm that pass but are marked as _untested_.

I'm planning to publish a new version of the library soon and document the outstanding issues with JSON-LD 1.1 compliance so that somebody can pick it up.

**Comment by kazarena** [comment]
The test suite is now using RDF dataset isomorphism when comparing n-quad results. See https://github.com/piprate/json-gold/pull/25.

**Comment by BigBlueHat** [comment]
Hey @kazarena! Thanks for implementing the JSON-LD 1.1 API. It looks like things have gone really well!

Could you submit the conformance report as a [pull request to the w3c/json-ld-api repo?](https://github.com/w3c/json-ld-api/pulls)? @gkellogg can work with you there on getting you added to the [final report](https://w3c.github.io/json-ld-api/reports/).

Thanks again!
🎩

**Comment by kazarena** [comment]
@BigBlueHat, I was just about to ask about it, following the discussion in the JSON-LD Working Group mailing list. I'll submit the report asap.

Stan

**Comment by kazarena** [comment]
@BigBlueHat I've pulled the latest official test suite in order to get a better alignment of test results (I used the version from early Jan 2020 previously). There's quite a bit of movement there, and I can see some easy targets to fix. I'll have to review and update them first before generating a new conformance report. It shouldn't take too long.

**Comment by kazarena** [comment]
@BigBlueHat ok, I've updated the test suite and generated the latest [conformance report](https://github.com/piprate/json-gold/blob/master/conformance_report.jsonld).

@gkellogg, looking at your [recent fixes](https://github.com/w3c/json-ld-api/pull/441/commits/5c7fc4d783c7062ca195e9a142052bf0e4a30be9), you expect "earl:test" to look like "https://w3c.github.io/json-ld-api/tests/testdata/expand-manifest#tc032", and not "https://w3c.github.io/json-ld-api/tests/testdata/expand-manifest.jsonld#tc032". Is that correct?

Is there anything else I should update in https://github.com/piprate/json-gold/blob/master/conformance_report.jsonld to reduce the amount of work required to incorporate the report?

Also, the framing implementation isn't updated to 1.1 yet, but is fully compatible with 1.0. What's the best way to report the test results? My report uses the test suite for JSON-LD Framing 1.0.

**Comment by gkellogg** [comment]
> @gkellogg, looking at your [recent fixes](https://github.com/w3c/json-ld-api/pull/441/commits/5c7fc4d783c7062ca195e9a142052bf0e4a30be9), you expect "earl:test" to look like "https://w3c.github.io/json-ld-api/tests/testdata/expand-manifest#tc032", and not "https://w3c.github.io/json-ld-api/tests/testdata/expand-manifest.jsonld#tc032". Is that correct?

Neither of those two (equivalent) URLs point to anything, as there is no "testdata" sub-directory. If they did, they would be to manifest entries. The suggested format is in the [preliminary report](https://w3c.github.io/json-ld-api/reports/). Best in Turtle format, but I can always convert the JSON-LD format to Turtle (you can use [my distiller](http://rdf.greggkellogg.net/distiller?command=serialize&format=jsonld&output_format=turtle) if you like).

```turtle
 [ a earl:Assertion;
    earl:assertedBy <--your-developer-identifier-->;
    earl:subject <--your-software-identifier-->;
    earl:test <--uri-of-test-from-manifest>;
    earl:result [
      a earl:TestResult;
      earl:outcome earl:passed;
      dc:date "2016-12-26T10:18:04-08:00"^^xsd:dateTime];
    earl:mode earl:automatic ] .

 <> foaf:primaryTopic <--your-software-identifier--> ;
    dc:issued "2016-12-26T10:18:04-08:00"^^xsd:dateTime ;
    foaf:maker <--your-developer-identifier--> .

  <--your-software-identifier--> a doap:Project, earl:TestSubject, earl:Software ;
    doap:name          "My Cool JSON-LD Parser" ;
    doap:release [
      doap:name     "--short name wih version number--";
      doap:revision "--Software version number--" ;
      doap:created  "2020-02-19"^^xsd:date;
    ] ;
    doap:developer     <--your-developer-identifier--> ;
    doap:homepage      <--your-software-homepace--> ;
    doap:description   "--your-project-description--"@en ;
    doap:programming-language "--your-implementation-language--" .
```

Note that the manifest IRIs used for identifying individual tests do not include the ".jsonld" extension, and there is no "testdata"  subdirectory, so `https://w3c.github.io/json-ld-api/tests/compact-manifest#t0001` and not `https://w3c.github.io/json-ld-api/tests/testdata/compact-manifest.jsonld#t0001`.

Also, note that the framing tests come from `https://w3c.github.io/json-ld-framing/tests/frame-manifest` not `https://w3c.github.io/json-ld-api/tests/compact-manifest`

You might also include a `doap:release` property referencing the `doap:revision` that you're reporting on.

With those changes I can generate a report, and I'll use this as the basis of doing an update, but for future reference please make sure the IRIs are right; if generating Turtle is a burden, it's easy enough to do on my end.

As it is, the summary information looks like the following:

<dl>
<dt id='subj_0'>
<span class='secno'>A.1</span>
<a href='https://github.com/piprate/json-gold'>
<span about='https://github.com/piprate/json-gold' property='doap:name'>JSON-goLD</span>
</a>
</dt>
<dd>
<dl>
<dt>Release</dt>
<dd property='doap:release'><span property='doap:revision'>unknown</span></dd>
<dt>Programming Language</dt>
<dd property='doap:programming-language'>Go</dd>
<dt>Home Page</dt>
<dd>
<a href='https://github.com/piprate/json-gold' property='doap:homepage'>
https://github.com/piprate/json-gold
</a>
</dd>
<dt>Developer</dt>
<dd rel='doap:developer'>
<div>
<a href='https://github.com/kazarena'>
<span property='foaf:name'>Stan Nazarenko</span>
</a>
<a href-@id='https://github.com/kazarena' href-@type='[&quot;Assertor&quot;, &quot;foaf:Person&quot;]' href-foaf:homepage='https://github.com/kazarena' href-foaf:name='Stan Nazarenko' property='foaf:homepage'>
https://github.com/kazarena
</a>
</div>
</dd>
<dt>
Test Suite Compliance
</dt>
<dd>
<table class='report'>
<tbody>
<tr>
<td>
Compaction
</td>
<td class='passed-most'>
232/238 (97.5%)
</td>
</tr>
<tr>
<td>
Expansion
</td>
<td class='passed-most'>
356/366 (97.3%)
</td>
</tr>
<tr>
<td>
Flattening
</td>
<td class='passed-all'>
55/55 (100.0%)
</td>
</tr>
<tr>
<td>
Remote document
</td>
<td class='passed-some'>
15/18 (83.3%)
</td>
</tr>
<tr>
<td>
Transform JSON-LD to RDF
</td>
<td class='passed-most'>
420/442 (95.0%)
</td>
</tr>
<tr>
<td>
Transform RDF to JSON-LD
</td>
<td class='passed-some'>
36/51 (70.6%)
</td>
</tr>
</tbody>
</table>
</dd>
</dl>
</dd>
</dl>


> Is there anything else I should update in https://github.com/piprate/json-gold/blob/master/conformance_report.jsonld to reduce the amount of work required to incorporate the report?

Thanks for thinking of this, just what I mentioned above.

> Also, the framing implementation isn't updated to 1.1 yet, but is fully compatible with 1.0. What's the best way to report the test results? My report uses the test suite for JSON-LD Framing 1.0.

Test with what you have, and it will show some level of compliance. You probably want to filter on `specVersion` and/or `processingMode`.

**Comment by gkellogg** [comment]
See https://github.com/w3c/json-ld-api/pull/447.

**Comment by kazarena** [comment]
@gkellogg thank you, I will address your feedback and update the conformance report.

Regarding the test suite for framing, I will try to update [the test suite] to 1.1 and see the level of conformance. Regardless of what the results are like, I will incorporate them into the conformance report to be consistent.

**Comment by kazarena** [comment]
@gkellogg please review the updated report [here](https://github.com/piprate/json-gold/blob/23aaa30e9f7c7cd4ac75127166ce11ae05eb52ad/conformance_report.jsonld). I refreshed the Framing tests too.

**Comment by gkellogg** [comment]
@kazarena Looks good, I'll update our report and push out shortly. Of course, you can always submit and update to your test results.
