### ISSUE TITLE
protected should be allowed

### ISSUE THREAD

**Issue by troyronda** [piprate/json-gold#22]
https://w3c.github.io/json-ld-api/#algorithm

> 5.13 For each key-value pair in context where key is not @ base, @ direction, @ import, @ language, @ propagate, @ protected, @ version, or @ vocab, invoke the Create Term Definition algorithm, passing result for active context, context for local context, key, defined, and the value of the @ protected entry from context, if any, for protected .

Example usage:
https://www.w3.org/2018/credentials/v1

Usage of this context results in an error:
```
Received unexpected error: invalid term definition: true
```

This error occurs because @ protected is not included in:
https://github.com/piprate/json-gold/blob/39d0d03253f6853fbf0fbf89053f836ef523cf9c/ld/context.go#L225

**Comment by kazarena** [comment]
@troyronda, many thanks for reporting. @protected is a part of JSON-LD 1.1 spec, which is only partially supported by this library. It's a relatively new term. We plan to bring compliance to 1.1 to 100% before the end of the year (but I can't promise that).

Regards,
Stan

**Comment by troyronda** [comment]
@kazarena Excellent - thanks for the quick reply!

**Comment by kazarena** [comment]
@troyronda I've created a new PR this implements the majority of the current JSON-LD 1.1 features, see https://github.com/piprate/json-gold/pull/24. I intend to publish a new version in the next couple of days. Watch this space!

**Comment by troyronda** [comment]
@kazarena Nice! Looking forward to the update :-).
