### ISSUE TITLE
Make rdfToObject public

### ISSUE THREAD

**Issue by iddan** [piprate/json-gold#32]
Hey, I'd like to use `rdfToObject()` in [cayleygraph/quad](https://github.com/cayleygraph/quad).
Is it possible to make it a public function so I'll be able to import it?

**Comment by kazarena** [comment]
@iddan yes, that makes sense. Will submit a PR today.

**Comment by iddan** [comment]
@kazarena Thank you!!!

**Comment by kazarena** [comment]
@iddan the fix has been merged into _master_. It will be included into a formal release later this week.
