### ISSUE TITLE
Respect RFC-7234 Caching Headers

### ISSUE THREAD

**Issue by Koshroy** [piprate/json-gold#6]
Having the document loader fetch documents to resolve IRIs constantly can get pretty expensive from a network bandwidth perspective. If there's interest, I can make a PR to add RFC-7234 support for caching.

**Comment by kazarena** [comment]
Hi @Koshroy, yes please make a PR. That would be great!

**Comment by kazarena** [comment]
This feature has been implemented by @Koshroy.
